### ISSUE TITLE
[WANT] 검색 기능시 보완 사항

### ISSUE THREAD

**Issue by jmlee119** [screeningHumanity/TMT-BE-SearchServer#7]
## 요청 구분
- [ ] 신규 요구 사항 발생
- [x] 수정 요청

## 요청 내용
 1. 주식/회원 검색 시, 리턴값 통일
 2. 검색어 하나라도 없으면 빈 배열 출력 (현재 400 Error 발생)
 3. 검색어가 최대 10개까지 출력됨
 4. 영어 대소문자 상관하지 않고 검색 필요. (LG, lg 둘중하나는 검색 안됨)
 5. 회원 검색 시, 닉네임으로 검색 되도록 수정.

## 기대 효과

**Comment by KangBaekGwa** [comment]
내용 확인하였습니다. 수정 진행 후, 멘션 남기겠습니다.

**Comment by KangBaekGwa** [comment]
@jmlee119 해당 내용 완료 되어, Issue Close 처리 하겠습니다.

**Comment by jmlee119** [comment]
> @jmlee119 해당 내용 완료 되어, Issue Close 처리 하겠습니다.
넵 확인했습니다
